#include "ShaderGenerator.h"

#include <sstream>

using namespace ailo::material;

namespace matcomp {

namespace {

const char* glslType(ParameterType type) {
    switch (type) {
        case ParameterType::Bool:           return "bool";
        case ParameterType::Bool2:          return "bvec2";
        case ParameterType::Bool3:          return "bvec3";
        case ParameterType::Bool4:          return "bvec4";
        case ParameterType::Float:          return "float";
        case ParameterType::Float2:         return "vec2";
        case ParameterType::Float3:         return "vec3";
        case ParameterType::Float4:         return "vec4";
        case ParameterType::Int:            return "int";
        case ParameterType::Int2:           return "ivec2";
        case ParameterType::Int3:           return "ivec3";
        case ParameterType::Int4:           return "ivec4";
        case ParameterType::UInt:           return "uint";
        case ParameterType::UInt2:          return "uvec2";
        case ParameterType::UInt3:          return "uvec3";
        case ParameterType::UInt4:          return "uvec4";
        case ParameterType::Float3x3:       return "mat3";
        case ParameterType::Float4x4:       return "mat4";
        case ParameterType::Sampler2D:      return "sampler2D";
        case ParameterType::SamplerCubemap: return "samplerCube";
    }
    return "?";
}

void define(std::ostringstream& out, const std::string& name, bool enabled = true) {
    if (enabled) out << "#define " << name << "\n";
}

// #line with a file name needs GL_GOOGLE_cpp_style_line_directive, which ShaderCompiler enables together with #include.
void lineDirective(std::ostringstream& out, int line, const std::string& sourceName) {
    std::string escaped;
    for (char c : sourceName) escaped += c == '\\' ? '/' : c;
    out << "#line " << line << " \"" << escaped << "\"\n";
}

void generateParameters(std::ostringstream& out, const MaterialPackage& pkg) {
    if (pkg.uniformBlockSize > 0) {
        out << "layout(set = 2, binding = " << kMaterialParamsBinding << ", std140) uniform MaterialParams {\n";
        for (const auto& p : pkg.parameters) {
            if (isSampler(p.type)) continue;
            out << "    " << glslType(p.type) << " " << p.name;
            if (p.arraySize) out << "[" << p.arraySize << "]";
            out << ";    // offset " << p.offset << "\n";
        }
        out << "} materialParams;\n";
    }
    for (const auto& p : pkg.parameters) {
        if (!isSampler(p.type)) continue;
        out << "layout(set = 2, binding = " << p.binding << ") uniform " << glslType(p.type)
            << " materialParams_" << p.name << ";\n";
    }
}

}

std::vector<Variant> getStageVariants(const MaterialDefinition& def, ShaderStage stage) {
    std::vector<Variant> variants;
    for (uint32_t key = 0; key < Variant::COUNT; key++) {
        Variant v { Variant::type_t(key) };
        if (!Variant::isValid(v) || (key & def.package.variantFilter)) continue;
        Variant filtered = stage == ShaderStage::Vertex ? Variant::filterVertex(v) : Variant::filterFragment(v);
        if (filtered == v) variants.push_back(v);
    }
    return variants;
}

std::string generateShader(const MaterialDefinition& def, ShaderStage stage, Variant variant, const std::string& sourceName) {
    const MaterialPackage& pkg = def.package;
    const bool vertex = stage == ShaderStage::Vertex;
    std::ostringstream out;

    out << "#version 450\n";
    out << "// Generated by matcomp from " << sourceName << " (" << toString(stage)
        << ", variant 0x" << std::hex << uint32_t(variant.key) << std::dec << "). Do not edit.\n\n";

    define(out, "VARIANT_HAS_SKINNING", vertex && variant.hasSkinning());
    define(out, "VARIANT_HAS_SHADOWING", !vertex && variant.isShadowReceiver());
    define(out, "VARIANT_DEPTH", variant.isDepth());
    // Depth variants skip materialVertex() unless the material moves its vertices.
    const bool optimizedDepth = vertex && variant.isDepth() && !def.hasClipPosition;
    define(out, "USE_OPTIMIZED_DEPTH_VERTEX_SHADER", optimizedDepth);

    define(out, "SHADING_MODEL_LIT", pkg.shadingModel == ShadingModel::Lit);
    define(out, "SHADING_MODEL_UNLIT", pkg.shadingModel == ShadingModel::Unlit);
    define(out, "HAS_ATTRIBUTE_COLOR", pkg.requiredAttributes & uint8_t(VertexAttribute::Color));
    define(out, "HAS_ATTRIBUTE_UV0", pkg.requiredAttributes & uint8_t(VertexAttribute::UV0));
    define(out, "HAS_ATTRIBUTE_TANGENTS", pkg.requiredAttributes & uint8_t(VertexAttribute::Tangents));
    define(out, "HAS_ATTRIBUTE_NORMAL", pkg.requiredAttributes & uint8_t(VertexAttribute::Normal));
    define(out, "MATERIAL_HAS_CLIP_POSITION", def.hasClipPosition);
    define(out, "MATERIAL_HAS_NORMAL", def.hasNormal);
    define(out, "MATERIAL_HAS_CUSTOM_SURFACE_SHADING", def.customSurfaceShading);
    for (size_t i = 0; i < pkg.variables.size(); i++) {
        out << "#define VARIABLE_CUSTOM" << i << " " << pkg.variables[i] << "\n";
        out << "#define VARIABLE_CUSTOM_AT" << i << " variable_" << pkg.variables[i] << "\n";
    }
    out << "\n";

    generateParameters(out, pkg);
    out << "\n";

    if (vertex) {
        out << "#include \"surface/surface_vertex.vs\"\n";
        if (!optimizedDepth) {
            if (def.vertex.present) {
                lineDirective(out, def.vertex.line, sourceName);
                out << def.vertex.code << "\n";
            } else {
                out << "void materialVertex(inout MaterialVertexInputs material) {}\n";
            }
        }
        out << "#include \"surface/surface_main.vs\"\n";
    } else if (variant.isDepth()) {
        out << "#include \"surface/surface_depth_main.fs\"\n";
    } else {
        out << "#include \"surface/surface_fragment.fs\"\n";
        lineDirective(out, def.fragment.line, sourceName);
        out << def.fragment.code << "\n";
        out << (pkg.shadingModel == ShadingModel::Lit
                    ? "#include \"surface/surface_shading_lit.fs\"\n"
                    : "#include \"surface/surface_shading_unlit.fs\"\n");
        out << "#include \"surface/surface_main.fs\"\n";
    }

    return out.str();
}

}
